spring:
  datasource:
    url: jdbc:h2:mem:ecommerce-db
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  web:
    resources:
      static-locations: file:uploads/
