spring:
  datasource:
    url: jdbc:h2:mem:ecommerce-db
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    root: info
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.server.authorization: DEBUG
