spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DATASOURCE_DB}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-group
      auto-offset-reset: earliest
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ecommerce-api
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/ecommerce
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce

brevo:
  api:
    key: ${MAIL_API_KEY}

email:
  from:
    name: ${EMAIL_FROM_NAME}
    address: ${EMAIL_FROM_ADDRESS}

keycloak:
  auth-server-url: http://localhost:8080
  realm: ecommerce
  client-id: ecommerce-api
  admin-username: ${KEYCLOAK_ADMIN_USER}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
